CREATE DATABASE `newyahoo` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `newyahoo`;

CREATE TABLE `checkers_admins` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` int(10) unsigned NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `checkers_games` (
  `game_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `players` blob,
  `oldratings` blob,
  `newratings` blob,
  `game_data` blob,
  `flags` bigint(20) unsigned DEFAULT NULL,
  `result` blob,
  PRIMARY KEY (`game_id`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8;

CREATE TABLE `checkers_ignoreds` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `ban_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ban_type` smallint(5) unsigned NOT NULL,
  `ban_time` bigint(20) NOT NULL,
  `reason` text NOT NULL,
  `admin` varchar(32) NOT NULL,
  `ip` varchar(16) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `checkers_profiles` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `rating` int(11) NOT NULL DEFAULT '1200',
  `wins` int(10) unsigned NOT NULL DEFAULT '0',
  `losses` int(10) unsigned NOT NULL DEFAULT '0',
  `draws` int(10) unsigned NOT NULL DEFAULT '0',
  `streak` int(11) NOT NULL DEFAULT '0',
  `aborteds` int(10) unsigned NOT NULL DEFAULT '0',
  `flags` bigint(20) unsigned NOT NULL,
  `ip` varchar(16) NOT NULL DEFAULT '0.0.0.0',
  PRIMARY KEY (`name`),
  KEY `index_2` (`ip`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `checkers_rooms` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `label` text,
  `public` tinyint(1) NOT NULL,
  `country` varchar(2) NOT NULL,
  `welcome_msg` text NOT NULL,
  `id_count` int(10) unsigned NOT NULL,
  PRIMARY KEY (`name`,`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `games` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `label` text,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ids` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` smallint(5) unsigned NOT NULL DEFAULT '0',
  `flags` bigint(20) unsigned NOT NULL DEFAULT '0',
  `more_flags` int(10) unsigned NOT NULL DEFAULT '0',
  `password` varchar(255) NOT NULL,
  `ycookie` varchar(72) NOT NULL DEFAULT '0',
  `e-mail` text NOT NULL,
  `ip` varchar(16) NOT NULL DEFAULT '0.0.0.0',
  `cookie_expires` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_access` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `avatar` smallint(5) unsigned NOT NULL DEFAULT '0',
  `friends` blob,
  `ignoreds` blob,
  `games_common_sound` tinyint(1) NOT NULL DEFAULT '1',
  `prowler_g` tinyint(1) NOT NULL DEFAULT '2',
  `games_common_profanity` smallint(5) unsigned NOT NULL DEFAULT '1',
  `games_common_hidestar` tinyint(1) NOT NULL DEFAULT '0',
  `games_common_smallwindows` tinyint(1) NOT NULL DEFAULT '0',
  `games_common_automove` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool2_admins` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` int(10) unsigned NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool2_games` (
  `game_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `players` blob,
  `oldratings` blob,
  `newratings` blob,
  `game_data` blob,
  `flags` bigint(20) unsigned DEFAULT NULL,
  `result` blob,
  PRIMARY KEY (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool2_ignoreds` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `ban_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ban_type` smallint(5) unsigned NOT NULL,
  `ban_time` bigint(20) NOT NULL,
  `reason` text NOT NULL,
  `admin` varchar(32) NOT NULL,
  `ip` varchar(16) NOT NULL,
  PRIMARY KEY (`name`,`admin`,`ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool2_profiles` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `rating` int(11) NOT NULL DEFAULT '1200',
  `wins` int(10) unsigned NOT NULL DEFAULT '0',
  `losses` int(10) unsigned NOT NULL DEFAULT '0',
  `draws` int(10) unsigned NOT NULL DEFAULT '0',
  `streak` int(11) NOT NULL DEFAULT '0',
  `aborteds` int(10) unsigned NOT NULL DEFAULT '0',
  `flags` bigint(20) unsigned NOT NULL,
  `ip` varchar(16) NOT NULL,
  PRIMARY KEY (`name`,`ip`),
  KEY `index_2` (`ip`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool2_rooms` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `label` text,
  `public` tinyint(1) NOT NULL,
  `country` varchar(2) NOT NULL,
  `welcome_msg` text NOT NULL,
  `id_count` int(10) unsigned NOT NULL,
  PRIMARY KEY (`name`,`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool_admins` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` int(10) unsigned NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool_games` (
  `game_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `players` blob,
  `oldratings` blob,
  `newratings` blob,
  `game_data` blob,
  `flags` bigint(20) unsigned DEFAULT NULL,
  `result` blob,
  PRIMARY KEY (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool_ignoreds` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `ban_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ban_type` smallint(5) unsigned NOT NULL,
  `ban_time` bigint(20) NOT NULL,
  `reason` text NOT NULL,
  `admin` varchar(32) NOT NULL,
  `ip` varchar(16) NOT NULL,
  PRIMARY KEY (`name`,`admin`,`ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool_profiles` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `rating` int(11) NOT NULL DEFAULT '1200',
  `wins` int(10) unsigned NOT NULL DEFAULT '0',
  `losses` int(10) unsigned NOT NULL DEFAULT '0',
  `draws` int(10) unsigned NOT NULL DEFAULT '0',
  `streak` int(11) NOT NULL DEFAULT '0',
  `aborteds` int(10) unsigned NOT NULL DEFAULT '0',
  `flags` bigint(20) unsigned NOT NULL,
  `ip` varchar(16) NOT NULL DEFAULT '0.0.0.0',
  PRIMARY KEY (`name`),
  KEY `index_2` (`ip`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pool_rooms` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `label` text,
  `public` tinyint(1) NOT NULL,
  `country` varchar(2) NOT NULL,
  `welcome_msg` text NOT NULL,
  `id_count` int(10) unsigned NOT NULL,
  PRIMARY KEY (`name`,`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `checkers_rooms` (`name`, `label`, `public`, `country`, `welcome_msg`, `id_count`) VALUES
('amoeba_drop', 'Amoeba Drop', 1, 'us', 'Welcome to room Amoeba Drop', 50),
('badger_bridge', 'Badger Bridge', 1, 'us', 'Welcome to room Badger Bridge', 50),
('beetle_spot', 'Beetle Spot', 1, 'us', 'Welcome to room Beetle Spot', 50),
('camel_club', 'Camel Club', 1, 'us', 'Welcome to room Camel Club', 50),
('cricket_cavern', 'Cricket Cavern', 1, 'us', 'Welcome to room Cricket Cavern', 50),
('ferret_hole', 'Ferret Hole', 1, 'us', 'Welcome to room Ferret Hole', 50),
('frog_pond', 'Frog Pond', 1, 'us', 'Welcome to room Frog Pond', 50),
('hamster_pit', 'Hamster Pit', 1, 'us', 'Welcome to room Hamster Pit', 50),
('hippo_swamp', 'Hippo Swamp', 1, 'us', 'Welcome to room Hippo Swamp', 50),
('lobster_lagoon', 'Lobster Lagoon', 1, 'us', 'Welcome to room Lobster Lagoon', 50),
('mosquito_pool', 'Mosquito Pool', 1, 'us', 'Welcome to room Mosquito Pool', 50),
('owl_tree', 'Owl Tree', 1, 'us', 'Welcome to room Owl Tree', 50),
('pelican_palace', 'Pelican Palace', 1, 'us', 'Welcome to room Pelican Palace', 50),
('ram_cliff', 'Ram Cliff', 1, 'us', 'Welcome to room Ram Cliff', 50),
('seahorse_grotto', 'Seahorse Grotto', 1, 'us', 'Welcome to room Seahorse Grotto', 50),
('tarantula_theatre', 'Tarantula Theatre', 1, 'us', 'Welcome to room Tarantula Theatre', 50),
('turtle_shell', 'Turtle Shell', 1, 'us', 'Welcome to room Turtle Shell', 50),
('walrus_rock', 'Walrus Rock', 1, 'us', 'Welcome to room Walrus Rock', 50),
('weasel_way', 'Weasel Way', 1, 'us', 'Welcome to room Weasel Way', 50),
('wombat_wagon', 'Wombat Wagon', 1, 'us', 'Welcome to room Wombat Wagon', 50),
('zebra_cove', 'Zebra Cove', 1, 'us', 'Welcome to room Zebra Cove', 50),
('rec_room', 'Rec Room', 1, 'us', 'Welcome to room Rec Room', 50),
('romper_room', 'Romper Room', 1, 'us', 'Welcome to room Romper Room', 50),
('rookies_rink', 'Rookies'' Rink', 1, 'us', 'Welcome to room Rookies'' Rink', 50),
('the_boardwalk', 'The Boardwalk', 1, 'us', 'Welcome to room The Boardwalk', 50),
('tin_pan_alley', 'Tin Pan Alley', 1, 'us', 'Welcome to room Tin Pan Alley', 50),
('challenging_cafe', 'Challenging Cafe', 1, 'us', 'Welcome to room Challenging Cafe', 50),
('decent_digs', 'Decent Digs', 1, 'us', 'Welcome to room Decent Digs', 50),
('aces_orbit', 'Ace''s Orbit', 1, 'us', 'Welcome to room Ace''s Orbit', 50),
('command_central', 'Command Central', 1, 'us', 'Welcome to room Command Central', 50),
('intense_city', 'Intense City', 1, 'us', 'Welcome to room Intense City', 50)
;


INSERT INTO `pool_rooms` (`name`, `label`, `public`, `country`, `welcome_msg`, `id_count`) VALUES
('argentina', 'Argentina', 1, 'ar', 'Welcome to room Argentina', 50),
('australia_and_nz', 'Australia & NZ', 1, 'au', 'Welcome to room Australia & NZ', 50),
('brazil', 'Brazil', 1, 'br', 'Welcome to room Brazil', 50),
('china', 'China', 1, 'cn', 'Welcome to room China', 50),
('germany', 'Germany', 1, 'de', 'Welcome to room Germany', 50),
('denmark', 'Denmark', 1, 'dk', 'Welcome to room Denmark', 50),
('espanol', 'Espanol', 1, 'es', 'Welcome to room Espanol', 50),
('spain', 'Spain', 1, 'es', 'Welcome to room Spain', 50),
('france', 'France', 1, 'fr', 'Welcome to room France', 50),
('uk_and_ireland', 'UK & Ireland', 1, 'gb', 'Welcome to room UK & Ireland', 50),
('hong_kong', 'Hong Kong', 1, 'hk', 'Welcome to room Hong Kong', 50),
('italy', 'Italy', 1, 'it', 'Welcome to room Italy', 50),
('mexico', 'Mexico', 1, 'mx', 'Welcome to room Mexico', 50),
('norway', 'Norway', 1, 'no', 'Welcome to room Norway', 50),
('sweden', 'Sweden', 1, 'se', 'Welcome to room Sweden', 50),
('8_ball_nightmare', '8 Ball Nightmare', 1, 'us', 'Welcome to room 8 Ball Nightmare', 50),
('a_face_in_the_crowd', 'A Face In The Crowd', 1, 'us', 'Welcome to room A Face In The Crowd', 50),
('achilles_last_stand', 'Achilles Last Stand', 1, 'us', 'Welcome to room Achilles Last Stand', 50),
('advanced_lounge', 'Advanced Lounge', 1, 'us', 'Welcome to room Advanced Lounge', 50),
('advanced_lounge_2', 'Advanced Lounge 2', 1, 'us', 'Welcome to room Advanced Lounge 2', 50),
('advanced_lounge_3', 'Advanced Lounge 3', 1, 'us', 'Welcome to room Advanced Lounge 3', 50),
('afraid_to_lose', 'Afraid To Lose', 1, 'us', 'Welcome to room Afraid To Lose', 50),
('alien', 'Alien', 1, 'us', 'Welcome to room Alien', 50),
('alive', 'Alive', 1, 'us', 'Welcome to room Alive', 50),
('alive_and_kicking', 'Alive And Kicking', 1, 'us', 'Welcome to room Alive And Kicking', 50),
('all_mixed_up', 'All Mixed Up', 1, 'us', 'Welcome to room All Mixed Up', 50),
('all_my_love', 'All My Love', 1, 'us', 'Welcome to room All My Love', 50),
('all_right_now', 'All Right Now', 1, 'us', 'Welcome to room All Right Now', 50),
('amsterdam_travellers', 'Amsterdam Travellers', 1, 'us', 'Welcome to room Amsterdam Travellers', 50),
('and_far_away', 'And Far Away', 1, 'us', 'Welcome to room And Far Away', 50),
('aneurysm', 'Aneurysm', 1, 'us', 'Welcome to room Aneurysm', 50),
('angel', 'Angel', 1, 'us', 'Welcome to room Angel', 50),
('anything_goes', 'Anything Goes', 1, 'us', 'Welcome to room Anything Goes', 50),
('avengers', 'Avengers', 1, 'us', 'Welcome to room Avengers', 50),
('baby_come_on_home', 'Baby Come On Home', 1, 'us', 'Welcome to room Baby Come On Home', 50),
('back_somersault', 'Back Somersault', 1, 'us', 'Welcome to room Back Somersault', 50),
('back_spin', 'Back Spin', 1, 'us', 'Welcome to room Back Spin', 50),
('back_to_school', 'Back to School', 1, 'us', 'Welcome to room Back to School', 50),
('backstreet_billiards', 'Backstreet Billiards', 1, 'us', 'Welcome to room Backstreet Billiards', 50),
('bad_apples', 'Bad Apples', 1, 'us', 'Welcome to room Bad Apples', 50),
('bad_times', 'Bad Times', 1, 'us', 'Welcome to room Bad Times', 50),
('banditos', 'Banditos', 1, 'us', 'Welcome to room Banditos', 50),
('bank_shot', 'Bank Shot', 1, 'us', 'Welcome to room Bank Shot', 50),
('battle_of_evermore', 'Battle Of Evermore', 1, 'us', 'Welcome to room Battle Of Evermore', 50),
('beer_lovers', 'Beer Lovers', 1, 'us', 'Welcome to room Beer Lovers', 50),
('beetle_spot', 'Beetle Spot', 1, 'us', 'Welcome to room Beetle Spot', 50),
('beginner_lounge', 'Beginner Lounge', 1, 'us', 'Welcome to room Beginner Lounge', 50),
('behind_the_8_ball', 'Behind The 8 Ball', 1, 'us', 'Welcome to room Behind The 8 Ball', 50),
('bent_cue', 'Bent Cue', 1, 'us', 'Welcome to room Bent Cue', 50),
('best_friends', 'Best Friends', 1, 'us', 'Welcome to room Best Friends', 50),
('bicycle_race', 'Bicycle Race', 1, 'us', 'Welcome to room Bicycle Race', 50),
('blurry', 'Blurry', 1, 'us', 'Welcome to room Blurry', 50),
('bohemian_rhapsody', 'Bohemian Rhapsody', 1, 'us', 'Welcome to room Bohemian Rhapsody', 50),
('bonzos_montreux', 'Bonzo''s Montreux', 1, 'us', 'Welcome to room Bonzo''s Montreux', 50),
('break_it_up', 'Break It Up', 1, 'us', 'Welcome to room Break It Up', 50),
('bring_it_on_home', 'Bring It On Home', 1, 'us', 'Welcome to room Bring It On Home', 50),
('brothers_in_arms', 'Brothers In Arms', 1, 'us', 'Welcome to room Brothers In Arms', 50),
('burning_for_you', 'Burning For You', 1, 'us', 'Welcome to room Burning For You', 50),
('by_myself', 'By Myself', 1, 'us', 'Welcome to room By Myself', 50),
('california_saloon', 'California Saloon', 1, 'us', 'Welcome to room California Saloon', 50),
('calling_elvis', 'Calling Elvis', 1, 'us', 'Welcome to room Calling Elvis', 50),
('candy_store_rock', 'Candy Store Rock', 1, 'us', 'Welcome to room Candy Store Rock', 50),
('celebration_day', 'Celebration Day', 1, 'us', 'Welcome to room Celebration Day', 50),
('center_spot', 'Center Spot', 1, 'us', 'Welcome to room Center Spot', 50),
('chalkies', 'Chalkies', 1, 'us', 'Welcome to room Chalkies', 50),
('champions_zone', 'Champions Zone', 1, 'us', 'Welcome to room Champions Zone', 50),
('coma', 'Coma', 1, 'us', 'Welcome to room Coma', 50),
('communication_breakdown', 'Communication Breakdown', 1, 'us', 'Welcome to room Communication Breakdown', 50),
('crazy_eights', 'Crazy Eights', 1, 'us', 'Welcome to room Crazy Eights', 50),
('crossed_cues', 'Crossed Cues', 1, 'us', 'Welcome to room Crossed Cues', 50),
('cruise', 'Cruise', 1, 'us', 'Welcome to room Cruise', 50),
('curmudgeon', 'Curmudgeon', 1, 'us', 'Welcome to room Curmudgeon', 50),
('cushion', 'Cushion', 1, 'us', 'Welcome to room Cushion', 50),
('custard_pie', 'Custard Pie', 1, 'us', 'Welcome to room Custard Pie', 50),
('dancing_days', 'Dancing Days', 1, 'us', 'Welcome to room Dancing Days', 50),
('dazed_and_confused', 'Dazed And Confused', 1, 'us', 'Welcome to room Dazed And Confused', 50),
('dont_cry', 'Don''t Cry', 1, 'us', 'Welcome to room Don''t Cry', 50),
('dont_stop_me_now', 'Don''t Stop Me Now', 1, 'us', 'Welcome to room Don''t Stop Me Now', 50),
('down_by_the_seaside', 'Down By The Seaside', 1, 'us', 'Welcome to room Down By The Seaside', 50),
('downtown', 'Downtown', 1, 'us', 'Welcome to room Downtown', 50),
('draw', 'Draw', 1, 'us', 'Welcome to room Draw', 50),
('dust_in_the_wind', 'Dust In The Wind', 1, 'us', 'Welcome to room Dust In The Wind', 50),
('east_side_cafe', 'East Side Cafe', 1, 'us', 'Welcome to room East Side Cafe', 50),
('eclipse', 'Eclipse', 1, 'us', 'Welcome to room Eclipse', 50),
('end_of_the_line', 'End Of The Line', 1, 'us', 'Welcome to room End Of The Line', 50),
('endless', 'Endless', 1, 'us', 'Welcome to room Endless', 50),
('english', 'English', 1, 'us', 'Welcome to room English', 50),
('estranged', 'Estranged', 1, 'us', 'Welcome to room Estranged', 50),
('europe_tour', 'Europe Tour', 1, 'us', 'Welcome to room Europe Tour', 50),
('fade', 'Fade', 1, 'us', 'Welcome to room Fade', 50),
('far_behind', 'Far Behind', 1, 'us', 'Welcome to room Far Behind', 50),
('fast_eddies', 'Fast Eddie''s', 1, 'us', 'Welcome to room Fast Eddie''s', 50),
('fearless', 'Fearless', 1, 'us', 'Welcome to room Fearless', 50),
('fire_and_rain', 'Fire And Rain', 1, 'us', 'Welcome to room Fire And Rain', 50),
('follow', 'Follow', 1, 'us', 'Welcome to room Follow', 50),
('fool_in_the_rain', 'Fool In The Rain', 1, 'us', 'Welcome to room Fool In The Rain', 50),
('foot_spot', 'Foot Spot', 1, 'us', 'Welcome to room Foot Spot', 50),
('for_you', 'For You', 1, 'us', 'Welcome to room For You', 50),
('for_your_life', 'For Your Life', 1, 'us', 'Welcome to room For Your Life', 50),
('forward_somersault', 'Forward Somersault', 1, 'us', 'Welcome to room Forward Somersault', 50),
('freshly_squeezed', 'Freshly Squeezed', 1, 'us', 'Welcome to room Freshly Squeezed', 50),
('front_rail', 'Front Rail', 1, 'us', 'Welcome to room Front Rail', 50),
('gallows_pole', 'Gallows Pole', 1, 'us', 'Welcome to room Gallows Pole', 50),
('garden_of_eden', 'Garden of Eden', 1, 'us', 'Welcome to room Garden of Eden', 50),
('get_in_the_ring', 'Get in the Ring', 1, 'us', 'Welcome to room Get in the Ring', 50),
('giving_in', 'Giving In', 1, 'us', 'Welcome to room Giving In', 50),
('gleason', 'Gleason', 1, 'us', 'Welcome to room Gleason', 50),
('going_to_california', 'Going To California', 1, 'us', 'Welcome to room Going To California', 50),
('good_times', 'Good Times', 1, 'us', 'Welcome to room Good Times', 50),
('grifters', 'Grifters', 1, 'us', 'Welcome to room Grifters', 50),
('handle_with_care', 'Handle With Care', 1, 'us', 'Welcome to room Handle With Care', 50),
('hangout', 'Hangout', 1, 'us', 'Welcome to room Hangout', 50),
('hats_off', 'Hats Off', 1, 'us', 'Welcome to room Hats Off', 50),
('head_rail', 'Head Rail', 1, 'us', 'Welcome to room Head Rail', 50),
('heartbreaker', 'Heartbreaker', 1, 'us', 'Welcome to room Heartbreaker', 50),
('heavy_fuel', 'Heavy Fuel', 1, 'us', 'Welcome to room Heavy Fuel', 50),
('hey_hey_what_can_i_do', 'Hey Hey What Can I Do', 1, 'us', 'Welcome to room Hey Hey What Can I Do', 50),
('high_rollers', 'High Rollers', 1, 'us', 'Welcome to room High Rollers', 50),
('hot_dog', 'Hot Dog', 1, 'us', 'Welcome to room Hot Dog', 50),
('i_cant_quit_you_baby', 'I Can''t Quit You Baby', 1, 'us', 'Welcome to room I Can''t Quit You Baby', 50),
('i_need_to_know', 'I Need To Know', 1, 'us', 'Welcome to room I Need To Know', 50),
('i_want_it_all', 'I Want It All', 1, 'us', 'Welcome to room I Want It All', 50),
('im_gonna_crawl', 'I''m Gonna Crawl', 1, 'us', 'Welcome to room I''m Gonna Crawl', 50),
('in_the_end', 'In The End', 1, 'us', 'Welcome to room In The End', 50),
('in_the_evening', 'In The Evening', 1, 'us', 'Welcome to room In The Evening', 50),
('in_the_light', 'In The Light', 1, 'us', 'Welcome to room In The Light', 50),
('intermediate_lounge', 'Intermediate Lounge', 1, 'us', 'Welcome to room Intermediate Lounge', 50),
('intermediate_lounge_2', 'Intermediate Lounge 2', 1, 'us', 'Welcome to room Intermediate Lounge 2', 50),
('intermediate_lounge_3', 'Intermediate Lounge 3', 1, 'us', 'Welcome to room Intermediate Lounge 3', 50),
('its_so_easy', 'It''s So Easy', 1, 'us', 'Welcome to room It''s So Easy', 50),
('jukebox', 'Jukebox', 1, 'us', 'Welcome to room Jukebox', 50),
('jump_shot', 'Jump Shot', 1, 'us', 'Welcome to room Jump Shot', 50),
('kashmir', 'Kashmir', 1, 'us', 'Welcome to room Kashmir', 50),
('kiss_the_rain', 'Kiss The Rain', 1, 'us', 'Welcome to room Kiss The Rain', 50),
('kitchen', 'Kitchen', 1, 'us', 'Welcome to room Kitchen', 50),
('lady_writer', 'Lady Writer', 1, 'us', 'Welcome to room Lady Writer', 50),
('last_nite', 'Last Nite', 1, 'us', 'Welcome to room Last Nite', 50),
('live_and_let_die', 'Live And Let Die', 1, 'us', 'Welcome to room Live And Let Die', 50),
('locomotive', 'Locomotive', 1, 'us', 'Welcome to room Locomotive', 50),
('lola', 'Lola', 1, 'us', 'Welcome to room Lola', 50),
('low_rollers', 'Low Rollers', 1, 'us', 'Welcome to room Low Rollers', 50),
('mama_kin', 'Mama Kin', 1, 'us', 'Welcome to room Mama Kin', 50),
('marigold', 'Marigold', 1, 'us', 'Welcome to room Marigold', 50),
('masse', 'Masse', 1, 'us', 'Welcome to room Masse', 50),
('minnesota_fats', 'Minnesota Fats', 1, 'us', 'Welcome to room Minnesota Fats', 50),
('misty_mountain_hop', 'Misty Mountain Hop', 1, 'us', 'Welcome to room Misty Mountain Hop', 50),
('moby_dick', 'Moby Dick', 1, 'us', 'Welcome to room Moby Dick', 50),
('money_for_nothing', 'Money For Nothing', 1, 'us', 'Welcome to room Money For Nothing', 50),
('mosquito_pool', 'Mosquito Pool', 1, 'us', 'Welcome to room Mosquito Pool', 50),
('my_michelle', 'My Michelle', 1, 'us', 'Welcome to room My Michelle', 50),
('my_world', 'My World', 1, 'us', 'Welcome to room My World', 50),
('nameless', 'Nameless', 1, 'us', 'Welcome to room Nameless', 50),
('newman', 'Newman', 1, 'us', 'Welcome to room Newman', 50),
('nicks_pool_parlor', 'Nick''s Pool Parlor', 1, 'us', 'Welcome to room Nick''s Pool Parlor', 50),
('night_flight', 'Night Flight', 1, 'us', 'Welcome to room Night Flight', 50),
('no_quarter', 'No Quarter', 1, 'us', 'Welcome to room No Quarter', 50),
('no_smoking', 'No Smoking', 1, 'us', 'Welcome to room No Smoking', 50),
('noble_game', 'Noble Game', 1, 'us', 'Welcome to room Noble Game', 50),
('obscured_by_clouds', 'Obscured By Clouds', 1, 'us', 'Welcome to room Obscured By Clouds', 50),
('once_upon_a_time', 'Once Upon A Time', 1, 'us', 'Welcome to room Once Upon A Time', 50),
('one_in_a_million', 'One In A Million', 1, 'us', 'Welcome to room One In A Million', 50),
('outlaws_revenge', 'Outlaw''s Revenge', 1, 'us', 'Welcome to room Outlaw''s Revenge', 50),
('over_the_hills', 'Over The Hills', 1, 'us', 'Welcome to room Over The Hills', 50),
('ozone_baby', 'Ozone Baby', 1, 'us', 'Welcome to room Ozone Baby', 50),
('paint_it_black', 'Paint It Black', 1, 'us', 'Welcome to room Paint It Black', 50),
('pandora', 'Pandora', 1, 'us', 'Welcome to room Pandora', 50),
('paradise_city', 'Paradise City', 1, 'us', 'Welcome to room Paradise City', 50),
('patience', 'Patience', 1, 'us', 'Welcome to room Patience', 50),
('pinball_wizard', 'Pinball Wizard', 1, 'us', 'Welcome to room Pinball Wizard', 50),
('play_the_game', 'Play The Game', 1, 'us', 'Welcome to room Play The Game', 50),
('players_choice', 'Player''s Choice', 1, 'us', 'Welcome to room Player''s Choice', 50),
('polly', 'Polly', 1, 'us', 'Welcome to room Polly', 50),
('pool_hustlers', 'Pool Hustlers', 1, 'us', 'Welcome to room Pool Hustlers', 50),
('pool_party', 'Pool Party', 1, 'us', 'Welcome to room Pool Party', 50),
('pool_sharks', 'Pool Sharks', 1, 'us', 'Welcome to room Pool Sharks', 50),
('poor_boy_blues', 'Poor Boy Blues', 1, 'us', 'Welcome to room Poor Boy Blues', 50),
('poor_tom', 'Poor Tom', 1, 'us', 'Welcome to room Poor Tom', 50),
('pretty_tied_up', 'Pretty Tied Up', 1, 'us', 'Welcome to room Pretty Tied Up', 50),
('prove_yourself', 'Prove Yourself', 1, 'us', 'Welcome to room Prove Yourself', 50),
('rack_em', 'Rack ''em', 1, 'us', 'Welcome to room Rack ''em', 50),
('rack_it_up', 'Rack It Up', 1, 'us', 'Welcome to room Rack It Up', 50),
('ramble_on', 'Ramble On', 1, 'us', 'Welcome to room Ramble On', 50),
('random', 'Random', 1, 'us', 'Welcome to room Random', 50),
('rat_race', 'Rat Race', 1, 'us', 'Welcome to room Rat Race', 50),
('rebels_loft', 'Rebel''s Loft', 1, 'us', 'Welcome to room Rebel''s Loft', 50),
('reckless_life', 'Reckless Life', 1, 'us', 'Welcome to room Reckless Life', 50),
('red_right_hand', 'Red Right Hand', 1, 'us', 'Welcome to room Red Right Hand', 50),
('rock_and_roll', 'Rock And Roll', 1, 'us', 'Welcome to room Rock And Roll', 50),
('rocket_queen', 'Rocket Queen', 1, 'us', 'Welcome to room Rocket Queen', 50),
('romeo_and_juliet', 'Romeo And Juliet', 1, 'us', 'Welcome to room Romeo And Juliet', 50),
('room_at_the_top', 'Room At The Top', 1, 'us', 'Welcome to room Room At The Top', 50),
('royal_orleans', 'Royal Orleans', 1, 'us', 'Welcome to room Royal Orleans', 50),
('sad', 'Sad', 1, 'us', 'Welcome to room Sad', 50),
('safety_dance', 'Safety Dance', 1, 'us', 'Welcome to room Safety Dance', 50),
('sandrines', 'Sandrine''s', 1, 'us', 'Welcome to room Sandrine''s', 50),
('sappy', 'Sappy', 1, 'us', 'Welcome to room Sappy', 50),
('save_me', 'Save Me', 1, 'us', 'Welcome to room Save Me', 50),
('scratch_that', 'Scratch That', 1, 'us', 'Welcome to room Scratch That', 50),
('sick_again', 'Sick Again', 1, 'us', 'Welcome to room Sick Again', 50),
('side_pocket', 'Side Pocket', 1, 'us', 'Welcome to room Side Pocket', 50),
('side_rail', 'Side Rail', 1, 'us', 'Welcome to room Side Rail', 50),
('skateaway', 'Skateaway', 1, 'us', 'Welcome to room Skateaway', 50),
('smoking_car', 'Smoking-car', 1, 'us', 'Welcome to room Smoking-car', 50),
('snookered', 'Snookered', 1, 'us', 'Welcome to room Snookered', 50),
('so_far_away', 'So Far Away', 1, 'us', 'Welcome to room So Far Away', 50),
('so_fine', 'So Fine', 1, 'us', 'Welcome to room So Fine', 50),
('social_lounge', 'Social Lounge', 1, 'us', 'Welcome to room Social Lounge', 50),
('social_lounge_10', 'Social Lounge 10', 1, 'us', 'Welcome to room Social Lounge 10', 50),
('social_lounge_2', 'Social Lounge 2', 1, 'us', 'Welcome to room Social Lounge 2', 50),
('social_lounge_3', 'Social Lounge 3', 1, 'us', 'Welcome to room Social Lounge 3', 50),
('social_lounge_4', 'Social Lounge 4', 1, 'us', 'Welcome to room Social Lounge 4', 50),
('social_lounge_5', 'Social Lounge 5', 1, 'us', 'Welcome to room Social Lounge 5', 50),
('social_lounge_6', 'Social Lounge 6', 1, 'us', 'Welcome to room Social Lounge 6', 50),
('social_lounge_7', 'Social Lounge 7', 1, 'us', 'Welcome to room Social Lounge 7', 50),
('social_lounge_8', 'Social Lounge 8', 1, 'us', 'Welcome to room Social Lounge 8', 50),
('social_lounge_9', 'Social Lounge 9', 1, 'us', 'Welcome to room Social Lounge 9', 50),
('somebody_to_love', 'Somebody To Love', 1, 'us', 'Welcome to room Somebody To Love', 50),
('something_in_the_air', 'Something In The Air', 1, 'us', 'Welcome to room Something In The Air', 50),
('stairway_to_heaven', 'Stairway To Heaven', 1, 'us', 'Welcome to room Stairway To Heaven', 50),
('stellar', 'Stellar', 1, 'us', 'Welcome to room Stellar', 50),
('stephens_dining_room', 'Stephen''s Dining Room', 1, 'us', 'Welcome to room Stephen''s Dining Room', 50),
('stickmen', 'Stickmen', 1, 'us', 'Welcome to room Stickmen', 50),
('straight_into_darkness', 'Straight Into Darkness', 1, 'us', 'Welcome to room Straight Into Darkness', 50),
('stripe_and_solid', 'Stripe and Solid', 1, 'us', 'Welcome to room Stripe and Solid', 50),
('sultans_of_swing', 'Sultans Of Swing', 1, 'us', 'Welcome to room Sultans Of Swing', 50),
('surrender', 'Surrender', 1, 'us', 'Welcome to room Surrender', 50),
('sweet_dreams', 'Sweet Dreams', 1, 'us', 'Welcome to room Sweet Dreams', 50),
('sweet_jane', 'Sweet Jane', 1, 'us', 'Welcome to room Sweet Jane', 50),
('sweet_melissa', 'Sweet Melissa', 1, 'us', 'Welcome to room Sweet Melissa', 50),
('tahiti', 'Tahiti', 1, 'us', 'Welcome to room Tahiti', 50),
('tangerine', 'Tangerine', 1, 'us', 'Welcome to room Tangerine', 50),
('tavern', 'Tavern', 1, 'us', 'Welcome to room Tavern', 50),
('tea_for_one', 'Tea For One', 1, 'us', 'Welcome to room Tea For One', 50),
('ten_years_gone', 'Ten Years Gone', 1, 'us', 'Welcome to room Ten Years Gone', 50),
('texas_farm', 'Texas Farm', 1, 'us', 'Welcome to room Texas Farm', 50),
('thats_the_way', 'That''s The Way', 1, 'us', 'Welcome to room That''s The Way', 50),
('the_buffalo_room', 'The Buffalo Room', 1, 'us', 'Welcome to room The Buffalo Room', 50),
('the_color_of_money', 'The Color Of Money', 1, 'us', 'Welcome to room The Color Of Money', 50),
('the_deep_end', 'The Deep End', 1, 'us', 'Welcome to room The Deep End', 50),
('the_nightingale', 'The Nightingale', 1, 'us', 'Welcome to room The Nightingale', 50),
('the_ocean', 'The Ocean', 1, 'us', 'Welcome to room The Ocean', 50),
('the_rover', 'The Rover', 1, 'us', 'Welcome to room The Rover', 50),
('the_show_must_go_on', 'The Show Must Go On', 1, 'us', 'Welcome to room The Show Must Go On', 50),
('the_wanton_song', 'The Wanton Song', 1, 'us', 'Welcome to room The Wanton Song', 50),
('there_she_goes', 'There She Goes', 1, 'us', 'Welcome to room There She Goes', 50),
('thorn_in_my_side', 'Thorn In My Side', 1, 'us', 'Welcome to room Thorn In My Side', 50),
('too_bad', 'Too Bad', 1, 'us', 'Welcome to room Too Bad', 50),
('topping', 'Topping', 1, 'us', 'Welcome to room Topping', 50),
('trampled_underfoot', 'Trampled Underfoot', 1, 'us', 'Welcome to room Trampled Underfoot', 50),
('travelling_riverside_blues', 'Travelling Riverside Blues', 1, 'us', 'Welcome to room Travelling Riverside Blues', 50),
('trick_shot', 'Trick Shot', 1, 'us', 'Welcome to room Trick Shot', 50),
('under_pressure', 'Under Pressure', 1, 'us', 'Welcome to room Under Pressure', 50),
('used_to_love_her', 'Used To Love Her', 1, 'us', 'Welcome to room Used To Love Her', 50),
('vegas', 'Vegas', 1, 'us', 'Welcome to room Vegas', 50),
('ventura_highway', 'Ventura Highway', 1, 'us', 'Welcome to room Ventura Highway', 50),
('vickis_secret', 'Vicki''s Secret', 1, 'us', 'Welcome to room Vicki''s Secret', 50),
('walk_away', 'Walk Away', 1, 'us', 'Welcome to room Walk Away', 50),
('walk_of_life', 'Walk Of Life', 1, 'us', 'Welcome to room Walk Of Life', 50),
('wasting_my_time', 'Wasting My Time', 1, 'us', 'Welcome to room Wasting My Time', 50),
('we_are_the_champions', 'We Are The Champions', 1, 'us', 'Welcome to room We Are The Champions', 50),
('we_will_rock_you', 'We Will Rock You', 1, 'us', 'Welcome to room We Will Rock You', 50),
('wearing_and_tearing', 'Wearing And Tearing', 1, 'us', 'Welcome to room Wearing And Tearing', 50),
('welcome_to_the_jungle', 'Welcome to the Jungle', 1, 'us', 'Welcome to room Welcome to the Jungle', 50),
('wet_bar', 'Wet Bar', 1, 'us', 'Welcome to room Wet Bar', 50),
('whatever', 'Whatever', 1, 'us', 'Welcome to room Whatever', 50),
('when_the_levee_breaks', 'When The Levee Breaks', 1, 'us', 'Welcome to room When The Levee Breaks', 50),
('whole_lotta_love', 'Whole Lotta Love', 1, 'us', 'Welcome to room Whole Lotta Love', 50),
('wild_eyes', 'Wild Eyes', 1, 'us', 'Welcome to room Wild Eyes', 50),
('wild_horses', 'Wild Horses', 1, 'us', 'Welcome to room Wild Horses', 50),
('wild_side', 'Wild Side', 1, 'us', 'Welcome to room Wild Side', 50),
('wild_thing', 'Wild Thing', 1, 'us', 'Welcome to room Wild Thing', 50),
('wombat_wagon', 'Wombat Wagon', 1, 'us', 'Welcome to room Wombat Wagon', 50),
('yesterdays', 'Yesterdays', 1, 'us', 'Welcome to room Yesterdays', 50),
('you_could_be_mine', 'You Could Be Mine', 1, 'us', 'Welcome to room You Could Be Mine', 50),
('you_got_lucky', 'You Got Lucky', 1, 'us', 'Welcome to room You Got Lucky', 50),
('youre_crazy', 'You''re Crazy', 1, 'us', 'Welcome to room You''re Crazy', 50),
('zebra_cove', 'Zebra Cove', 1, 'us', 'Welcome to room Zebra Cove', 50)
;

UPDATE `pool_rooms` SET `public` = 0;
UPDATE `pool_rooms` SET `public` = 1
WHERE `name` IN (
  'advanced_lounge',
  'beginner_lounge',
  'intermediate_lounge',
  'social_lounge',
  '8_ball_nightmare',
  'fast_eddies',
  'high_rollers',
  'low_rollers',
  'minnesota_fats',
  'players_choice',
  'pool_hustlers',
  'pool_sharks',
  'rack_it_up',
  'side_pocket',
  'trick_shot'
);




